### ISSUE TITLE
anycable-go: Auth failed

### ISSUE THREAD

**Issue by charlie-wasp** [palkan/any_cable_app#2]
Hello!

I am trying to launch this application, and still have no luck.

In the logs for `go` I see this:
```
go  | Running websocket server on 0.0.0.0:8080
...
go  | Auth Failed
```
I run it on linux machine, so I compiled [anycable-go](https://github.com/anycable/anycable-go) with `make` and then ran `cp $GOPATH/bin/anycable-go ~/code/anycable/anycable_demo/bin/`

Where the problem can be? Unfortunately, I don't have any experience with Go yet, so I could not determine a source of trouble by myself.

I used hivemind to start application.

**Comment by palkan** [comment]
Hi, @charlie-wasp!

It looks like your cookies don't contain required key or unaccessible to the Go server ([this line](https://github.com/anycable/anycable_demo/blob/master/app/channels/application_cable/connection.rb#L13) causes authorization failure).

Make sure that you're running Rails app and Go server on the same host (e.g. `0.0.0.0`) so they can share cookies.

Or you can temporarily disable the authentication with `SKIP_AUTH=1` env variable.

**Comment by palkan** [comment]
I guess, you're trying to access the app on `localhost:3000`? Am I right? Then try `0.0.0.0:3000`, because Go server runs on `0.0.0.0` by default.

**Comment by charlie-wasp** [comment]
@palkan yes, `0.0.0.0` did the trick! Thank you for your help. Never heard of using that kind ip in the browser.

Maybe it worth noting in the README? It can save some time for future users.

**Comment by palkan** [comment]
I think it's better to make it work on `localhost` by default)

**Comment by palkan** [comment]
Done.
