### ISSUE TITLE
Add redis-server into Procfile?

### ISSUE THREAD

**Issue by sadovnik** [palkan/any_cable_app#3]
Hello, Vladimir!

I came here again to take another attempt to dive into Anycable and help you to build Anycablebility. 

Anyway, this issue is not about this. : )

I get this error when I run the demo via hivemind:

```
go  | Running websocket server on localhost:3334 at /cable
go  | dial tcp [::1]:6379: getsockopt: connection refused
go  | failed to subscibe to Redis: dial tcp [::1]:6379: getsockopt: connection refused
```

As seen, It's simply because I have no `redis-server` running in the background.

I thought it would be helpful, if we add `redis-server` right into the `Procfile`, since it's only for demonstration purpose:
```
redis: [[ $(lsof -i :6379) ]] && tail -f /dev/null || redis-server
```

What do you think? : )

**Comment by palkan** [comment]
Hi, Cyril!

We already have Redis in the of  our _Requirements_ (as long as PostgreSQL), so it should be clear that Redis server must be running. 
Procfile should contain only the application processes. Database is not that one.

**Comment by sadovnik** [comment]
Oh, I haven't noticed PostgreSQL. Alright, this makes sense now.
