### ISSUE TITLE
Duplicated Request

### ISSUE THREAD

**Issue by anhtai87-zz** [palkan/any_cable_app#5]
Dear,

I used Docker to run this application demo.
When I visited localhost:3000, I saw the request was duplicated in the log file.
Here my log:

> app_1       | Started GET "/" for 172.17.0.1 at 2018-04-06 07:47:22 +0000
> app_1       | Started GET "/" for 172.17.0.1 at 2018-04-06 07:47:22 +0000
> app_1       |    (1.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
> app_1       |    (1.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
> app_1       | Processing by BasketsController#index as HTML
> app_1       | Processing by BasketsController#index as HTML
> app_1       |   Rendering baskets/index.slim within layouts/application
> app_1       |   Rendering baskets/index.slim within layouts/application

Do anyone have the same error? 
Thanks,

**Comment by palkan** [comment]
Hi @anhtai87,


Confirm; I see the same. There is a duplicated log, not duplicated request.
That happen only in development.

**Comment by palkan** [comment]
Should be fixed in 0.5.4
